### ISSUE TITLE
示例数据问题

### ISSUE THREAD

**Issue by MuyuenLP** [xwxztq/CBC2023#1]
您好
请问在datas文件夹下的示例数据中，d1u5ka2.ent中，有一行REMARK  99 ASTRAL SCOPe-sccs: g.45.1.2，这是不是应该说明此蛋白质属于g.45.1，而不是out.lst中的g.39.1

**Comment by xwxztq** [comment]
您好。
是的，您的理解没有问题。
两个pdb（ent）文件中的对应部分确实为SCOPe的分类，但是在**实际的测试示例**中并不会包含该字段。
在out.lst中是程序输出的结果，是为了演示评分过程。
感谢您的反馈，我们将在README里添加相应的说明。
